Submission
Alvaro8gb/OS_Python pull request #7
Opened 2024-03-07 21:35 UTC by arvmarandi

Here is my initial submission.

2024-03-07 21:35 UTC, arvmarandi commented
Here is my initial submission.

2024-03-09 09:27 UTC, Alvaro8gb requested changes
Ist okey but you can improve

2024-03-09 09:27 UTC, Alvaro8gb commented on work/Arvand/Exercise1.3.png
I cant see any zombie

2024-03-09 09:27 UTC, Alvaro8gb commented on work/Arvand/daemon.py
> +    with open("daemon_function.py", "r") as file:
good

2024-03-09 09:27 UTC, Alvaro8gb commented on work/Arvand/killer.py
> +    print(f"parent process with PID: {os.getpid()}, my child's PID is: {pid}")
good

2024-03-09 09:27 UTC, Alvaro8gb commented on work/Arvand/Exercise1.2.py
> +
system is high level fuction using exec is best

2024-03-09 09:27 UTC, Alvaro8gb commented on work/Arvand/Exercise1.1.py
> +
the parents shouldd wait

2024-03-09 12:27 UTC, closed without merging